export enum EmailChangeStatus {
  PENDING_OLD_EMAIL = "PENDING_OLD_EMAIL",
  PENDING_NEW_EMAIL = "PENDING_NEW_EMAIL",
  COMPLETED = "COMPLETED",
  EXPIRED = "EXPIRED",
  CANCELLED = "CANCELLED",
}

export const EMAIL_CHANGE_EXPIRY_MINUTES = 30;
